// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://rozkooglygxyaaedvebn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJvemtvb2dseWd4eWFhZWR2ZWJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA2OTM0ODksImV4cCI6MjA3NjI2OTQ4OX0.QJGgshn3Cio7BXRyGIvuq1LLT_xiGNb_rVWjlc17gQc";

// Intercepter les erreurs de console pour masquer les erreurs de refresh token attendues
const originalConsoleError = console.error;
console.error = (...args: any[]) => {
  const message = args[0]?.toString() || '';
  // Ignorer les erreurs de refresh token connues (elles sont gérées silencieusement)
  if (
    message.includes('Invalid Refresh Token') ||
    message.includes('refresh_token_not_found') ||
    message.includes('AuthApiError')
  ) {
    return; // Ne pas afficher ces erreurs
  }
  originalConsoleError.apply(console, args);
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
  },
  global: {
    headers: {
      'x-application-name': 'MyHealthPlus',
    },
  },
});